/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author igorf
 */
public class Interface extends javax.swing.JPanel {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abaFundoInterface = new javax.swing.JTabbedPane();
        abaHome = new javax.swing.JPanel();
        fundoPrincipal = new javax.swing.JLabel();
        abaCadastro = new javax.swing.JPanel();
        escritaCadastrarCliente = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        escritaNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        escritaEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        escritaCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        escritaTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        bordaAcima = new javax.swing.JLabel();
        escritaPesquisarCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePesquisarCliente = new javax.swing.JTable();
        bordaAbaixo = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        bordaDireita = new javax.swing.JLabel();
        fundoSecundario = new javax.swing.JLabel();
        abaMultas = new javax.swing.JPanel();
        fundoTerciario = new javax.swing.JLabel();
        abaEmprestimos = new javax.swing.JPanel();
        fundoQuaternario = new javax.swing.JLabel();

        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(800, 513));
        setMinimumSize(new java.awt.Dimension(800, 513));
        setPreferredSize(new java.awt.Dimension(800, 513));

        abaFundoInterface.setToolTipText("");
        abaFundoInterface.setMaximumSize(new java.awt.Dimension(800, 513));
        abaFundoInterface.setMinimumSize(new java.awt.Dimension(800, 513));
        abaFundoInterface.setName(""); // NOI18N

        abaHome.setLayout(null);

        fundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/images/img.principal.png"))); // NOI18N
        fundoPrincipal.setText("jLabel1");
        abaHome.add(fundoPrincipal);
        fundoPrincipal.setBounds(0, 0, 800, 480);

        abaFundoInterface.addTab("HOME", abaHome);

        abaCadastro.setLayout(null);

        escritaCadastrarCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        escritaCadastrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        escritaCadastrarCliente.setText("Cadastrar Cliente");
        abaCadastro.add(escritaCadastrarCliente);
        escritaCadastrarCliente.setBounds(10, 10, 140, 16);

        btnCadastrar.setBackground(new java.awt.Color(153, 153, 153));
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.setMaximumSize(new java.awt.Dimension(75, 23));
        btnCadastrar.setMinimumSize(new java.awt.Dimension(75, 23));
        abaCadastro.add(btnCadastrar);
        btnCadastrar.setBounds(640, 50, 130, 23);

        escritaNome.setForeground(new java.awt.Color(255, 255, 255));
        escritaNome.setText("Nome:");
        escritaNome.setToolTipText("");
        abaCadastro.add(escritaNome);
        escritaNome.setBounds(30, 40, 37, 16);
        abaCadastro.add(txtNome);
        txtNome.setBounds(90, 40, 330, 22);

        escritaEmail.setForeground(new java.awt.Color(255, 255, 255));
        escritaEmail.setText("Email:");
        abaCadastro.add(escritaEmail);
        escritaEmail.setBounds(30, 70, 37, 16);
        abaCadastro.add(txtEmail);
        txtEmail.setBounds(90, 70, 330, 22);

        escritaCpf.setForeground(new java.awt.Color(255, 255, 255));
        escritaCpf.setText("CPF:");
        abaCadastro.add(escritaCpf);
        escritaCpf.setBounds(30, 100, 37, 16);
        abaCadastro.add(txtCpf);
        txtCpf.setBounds(90, 100, 330, 22);

        escritaTelefone.setForeground(new java.awt.Color(255, 255, 255));
        escritaTelefone.setText("Telefone:");
        abaCadastro.add(escritaTelefone);
        escritaTelefone.setBounds(30, 130, 70, 16);
        abaCadastro.add(txtTelefone);
        txtTelefone.setBounds(90, 130, 330, 22);

        bordaAcima.setToolTipText("");
        bordaAcima.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        abaCadastro.add(bordaAcima);
        bordaAcima.setBounds(10, 30, 780, 140);

        escritaPesquisarCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        escritaPesquisarCliente.setForeground(new java.awt.Color(255, 255, 255));
        escritaPesquisarCliente.setText("Pesquisar Cliente");
        abaCadastro.add(escritaPesquisarCliente);
        escritaPesquisarCliente.setBounds(10, 180, 140, 25);

        tablePesquisarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Email", "Cpf", "Telefone", "Emprestimos", "Pendências"
            }
        ));
        jScrollPane1.setViewportView(tablePesquisarCliente);

        abaCadastro.add(jScrollPane1);
        jScrollPane1.setBounds(22, 222, 570, 220);

        bordaAbaixo.setToolTipText("");
        bordaAbaixo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        abaCadastro.add(bordaAbaixo);
        bordaAbaixo.setBounds(10, 210, 590, 240);

        btnExcluir.setBackground(new java.awt.Color(153, 153, 153));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("EXCLUIR");
        abaCadastro.add(btnExcluir);
        btnExcluir.setBounds(650, 420, 130, 23);

        btnAlterar.setBackground(new java.awt.Color(153, 153, 153));
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("ALTERAR");
        btnAlterar.setMaximumSize(new java.awt.Dimension(75, 23));
        btnAlterar.setMinimumSize(new java.awt.Dimension(75, 23));
        abaCadastro.add(btnAlterar);
        btnAlterar.setBounds(650, 230, 130, 23);

        bordaDireita.setToolTipText("");
        bordaDireita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        abaCadastro.add(bordaDireita);
        bordaDireita.setBounds(630, 210, 160, 250);

        fundoSecundario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/images/img.fundo.jpg"))); // NOI18N
        fundoSecundario.setText("jLabel2");
        abaCadastro.add(fundoSecundario);
        fundoSecundario.setBounds(0, 0, 800, 480);

        abaFundoInterface.addTab("CADASTRAR", abaCadastro);

        abaMultas.setLayout(null);

        fundoTerciario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/images/img.fundo.jpg"))); // NOI18N
        fundoTerciario.setText("jLabel2");
        abaMultas.add(fundoTerciario);
        fundoTerciario.setBounds(0, 0, 800, 480);

        abaFundoInterface.addTab("MULTAS", abaMultas);

        abaEmprestimos.setLayout(null);

        fundoQuaternario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/images/img.fundo.jpg"))); // NOI18N
        fundoQuaternario.setText("jLabel2");
        abaEmprestimos.add(fundoQuaternario);
        fundoQuaternario.setBounds(0, 0, 800, 480);

        abaFundoInterface.addTab("EMPRÉSTIMOS", abaEmprestimos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abaFundoInterface, javax.swing.GroupLayout.PREFERRED_SIZE, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abaFundoInterface, javax.swing.GroupLayout.PREFERRED_SIZE, 466, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaCadastro;
    private javax.swing.JPanel abaEmprestimos;
    private javax.swing.JTabbedPane abaFundoInterface;
    private javax.swing.JPanel abaHome;
    private javax.swing.JPanel abaMultas;
    private javax.swing.JLabel bordaAbaixo;
    private javax.swing.JLabel bordaAcima;
    private javax.swing.JLabel bordaDireita;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel escritaCadastrarCliente;
    private javax.swing.JLabel escritaCpf;
    private javax.swing.JLabel escritaEmail;
    private javax.swing.JLabel escritaNome;
    private javax.swing.JLabel escritaPesquisarCliente;
    private javax.swing.JLabel escritaTelefone;
    private javax.swing.JLabel fundoPrincipal;
    private javax.swing.JLabel fundoQuaternario;
    private javax.swing.JLabel fundoSecundario;
    private javax.swing.JLabel fundoTerciario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePesquisarCliente;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
